workspace:
  base: /srv/app

clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  build:
    image: node
    pull: true
    group: build-static
    commands:
      - npm install
      - npm run lint
      - npm run build
    when:
      event: [push, tag, pull_request]

  static:
    image: karalabe/xgo-latest:latest
    pull: true
    commands:
      - cd dist
      - zip -r ../vikunja-frontend.zip *
      - cd ..
    when:
      event: [tag, push]

  # Push the releases to our pseudo-s3-bucket
  release:
    image: plugins/s3:1
    pull: true
    secrets: [ aws_access_key_id, aws_secret_access_key ]
    bucket: vikunja
    endpoint: https://storage.kolaente.de
    path_style: true
    source: vikunja-frontend.zip
    target: /${DRONE_TAG##v}
    when:
      event: [ tag ]

  release:
    image: plugins/s3:1
    pull: true
    secrets: [ aws_access_key_id, aws_secret_access_key ]
    bucket: vikunja
    endpoint: https://storage.kolaente.de
    path_style: true
    source: vikunja-frontend.zip
    target: /master
    when:
      event: [ push ]
      branch: [ master ]

