kind: pipeline
name: release-latest

trigger:
  branch:
    - master
  event:
    - push

steps:
  - name: fetch-tags
    image: docker:git
    commands:
      - git fetch --tags

  - name: build
    image: electronuserland/builder:wine
    pull: true
    depends_on: [ fetch-tags ]
    commands:
      # TODO: Move to a yarn script
      - wget https://dl.vikunja.io/frontend/vikunja-frontend-master.zip
      - unzip vikunja-frontend-master.zip -d frontend
      - sed -i 's/\\/api\\/v1//g' frontend/index.html
      # Make sure that the -master suffix is added to release files
      - export VERSION=${DRONE_TAG##v}
      - if [ -z "$$VERSION" ]; then export VERSION=${DRONE_BRANCH}; fi
      - sed -i "s/\$${version}/$$VERSION/g" package.json
      - yarn install
      - yarn dist --linux --windows

  - name: release
    image: plugins/s3:1
    pull: true
    settings:
      bucket: vikunja-releases
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      endpoint: https://s3.fr-par.scw.cloud
      region: fr-par
      path_style: true
      strip_prefix: dist/
      source: dist/*
      target: /desktop/master/
    depends_on: [ build ]

