version: '3'

services:
  api:
    image: vikunja/api
    environment:
      VIKUNJA_LOG_LEVEL: DEBUG
      VIKUNJA_SERVICE_TESTINGTOKEN: averyLongSecretToSe33dtheDB
  cypress:
    image: cypress/browsers:node12.18.3-chrome87-ff82
    volumes:
    - ..:/project
    - $HOME/.cache:/home/node/.cache/
    user: node
    working_dir: /project
    environment:
      CYPRESS_API_URL: http://api:3456/api/v1
      CYPRESS_TEST_SECRET: averyLongSecretToSe33dtheDB
