version: '3'

services:
  api:
    image: vikunja/api:unstable
    environment:
      VIKUNJA_LOG_LEVEL: DEBUG
      VIKUNJA_SERVICE_TESTINGTOKEN: averyLongSecretToSe33dtheDB
    ports:
      - 3456:3456
  cypress:
    image: cypress/browsers:node16.14.0-chrome99-ff97
    volumes:
    - ..:/project
    - $HOME/.cache:/home/node/.cache/
    user: node
    working_dir: /project
    environment:
      CYPRESS_API_URL: http://api:3456/api/v1
      CYPRESS_TEST_SECRET: averyLongSecretToSe33dtheDB
