services:
  dex:
    image: ghcr.io/go-vikunja/dex-testing:main@sha256:e3749042425121410a6a562395c17413d4bc32bb9c99e03bd0298d92ca3445f0
    ports:
      - 5556:5556
  cypress:
    image: cypress/browsers:latest@sha256:79a28dd47913b1cca9fdd9d763f587b4660ee2c269d941c1903135399f4a9f20
    volumes:
      - ..:/project
      - $HOME/.cache:/home/node/.cache/
    user: node
    working_dir: /project
    environment:
      CYPRESS_API_URL: http://api:3456/api/v1
      CYPRESS_TEST_SECRET: averyLongSecretToSe33dtheDB
